name: Bug report
description: Template for bug reports
title: '[Bug]: '
labels:
  - 'Type: Bug'
body:
  - type: checkboxes
    id: consent
    attributes:
      label: Consent
      description: I agree with the following sentences and know that the ticket can get closed if I'm not truthful with my answers
      options:
        - label: I have searched the existing issues and verified that there is no existing issue (open or closed) for the same subject.
          required: true
        - label: I understand that YouTube Music Streamer has NO affiliation with Google, YouTube or the YTMDesktop application.
          required: true
        - label: I have visited the help desk page and couldn’t find any information on this topic or anything that could help me.
          required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current behavior
      description: A concise description of what you're experiencing. Please provide screenshots as well, if applicable.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...' 
        2. Click on '....' 
        3. Scroll down to '.....' 
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: os-arch
    attributes:
      label: OS Architecture
      description: Which type of architecture is your operation system?
      options:
        - x64
        - x32
        - arm64
    validations:
      required: true
  - type: dropdown
    id: installer-type
    attributes:
      label: File type
      description: What file did you download?
      options:
        - x64 Installer
        - x64 Portable
        - x32 Installer
        - x32 Portable
        - arm64 Installer
        - arm64 Portable
    validations:
      required: true
  - type: input
    id: application-version
    attributes:
      label: Application Version
      description: On what version are you currently? (You can check this by clicking on about in the bottom left)
      placeholder: v1.2.3
    validations:
      required: true
  - type: input
    id: ytmdesktop-version
    attributes:
      label: YTMDesktop Version
      description: Which YTMDesktop Version are you using?
      placeholder: v1.2.3
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering! 
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.