name: Ask a Question
description: Template for asking a question
title: '[Question]: '
labels:
  - 'Type: Question'
body:
  - type: checkboxes
    id: consent
    attributes:
      label: Consent
      description: I agree with the following sentences and know that the ticket can get closed if I'm not truthful with my answers
      options:
        - label: I have searched the existing issues and verified that there is no existing issue (open or closed) for the same subject.
          required: true
        - label: I understand that YouTube Music Streamer has NO affiliation with Google, YouTube or the YTMDesktop application.
          required: true
        - label: I have visited the help desk page and couldn’t find any information on this topic or anything that could help me.
          required: true
  - type: textarea
    id: question
    attributes:
      label: Question
      description: A concise description of the question you would like to ask.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering! 
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false