// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouTubeMusicStreamer.Services.App.Persistence;

#nullable disable

namespace YouTubeMusicStreamer.Services.App.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324202658_RemoveTwitchChatChannel")]
    partial class RemoveTwitchChatChannel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("YouTubeMusicStreamer.Services.App.Persistence.AppConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LogLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppConfiguration");
                });

            modelBuilder.Entity("YouTubeMusicStreamer.Services.App.Persistence.BlacklistEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlacklistEntries");
                });

            modelBuilder.Entity("YouTubeMusicStreamer.Services.App.Persistence.CommandConfigurationEntity", b =>
                {
                    b.Property<string>("CommandKey")
                        .HasColumnType("TEXT");

                    b.Property<uint>("BitsThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatTriggerMode")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagedRewardName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardBroadcasterAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RewardTriggerMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CommandKey");

                    b.ToTable("CommandConfigurations");
                });

            modelBuilder.Entity("YouTubeMusicStreamer.Services.App.Persistence.QueueItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmbedJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requester")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.ToTable("QueueItems");
                });

            modelBuilder.Entity("YouTubeMusicStreamer.Services.App.Persistence.QueueSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("QueueActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("QueueItemAsIFrame")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QueueSettings");
                });

            modelBuilder.Entity("YouTubeMusicStreamer.Services.App.Persistence.TwitchSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BotAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BotDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BotLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("BotProfileImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("BroadcasterAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BroadcasterDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BroadcasterLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("BroadcasterProfileImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SendMessageOnConnect")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TwitchSettings");
                });

            modelBuilder.Entity("YouTubeMusicStreamer.Services.App.Persistence.YouTubeSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAudioCapture")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioCaptureDevice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoStartServer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("YouTubeSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
